### ISSUE TITLE
Familiar forward deletion keyboard shortcut Ctrl-D

### ISSUE THREAD

**Issue by villelaitila** [asottile/babi#101]
Many developers and shell users are used to forward delete characters with Ctrl-D. In bash and zsh, if there are any character under the cursor, that is deleted with it. Also nano behaves similarly.

So, I argue that it would be consistent (with the rest of the world) to also let users to do forward delete with Ctrl-D, and therefore implement that binding in babi also, as babi is already consistent with nano in so many other ways.

**Comment by asottile** [comment]
yep seems fine, would you like to send a patch? basically you would add an alias [here](https://github.com/asottile/babi/blob/604942306ff59ad5311b0e1005a66251bd1a85f0/babi/file.py#L760)

probably `^D` to `delete`

**Comment by villelaitila** [comment]
I'll work on this

**Comment by villelaitila** [comment]
Published in v0.0.19
