### ISSUE TITLE
Improve documentation for developers

### ISSUE THREAD

**Issue by villelaitila** [asottile/babi#105]
README:md should give info on how to install required dev dependencies and how to run the unit tests. E.g. installation of tmux is not mentioned anywhere.

**Comment by asottile** [comment]
I tend to disagree on this, I realize it's a little slower to set up, but it removes the need to keep those in sync.  A `tox.ini` file is a clear indication that `tox` should be used to test (and is a pretty normal expectation for a python project).  Also `FileNotFound: tmux` is also a good enough error message in my opinion.
