### ISSUE TITLE
Add a "Why Babi" section to the docs

### ISSUE THREAD

**Issue by rmorshea** [asottile/babi#110]
It would be good to explain why you would choose `babi` over `nano` since the comparison is pretty easy to make given the name and interface.

**Comment by asottile** [comment]
fortunately I recorded a video about it :) https://www.youtube.com/watch?v=WyR1hAGmR3g

**Comment by rmorshea** [comment]
Maybe just linking to the video starting at 3:13 then?

https://www.youtube.com/watch?v=WyR1hAGmR3g&feature=youtu.be&t=193
