### ISSUE TITLE
Infinite hang with particular shell script

### ISSUE THREAD

**Issue by asottile** [asottile/babi#120]
Open `t.sh`

Paste this:

```bash
set -euxo pipefail

! (python3 -m pyflakes t.py || true) | grep ._array_like.ArrayLike
```

Put a paren before the first `(`

**Comment by AndrewLaneX** [comment]
Just `((` causes it to hang too.

**Comment by asottile** [comment]
ended up fixing the shellscript grammar -- bump to `babi-grammars>=0.0.26`
