### ISSUE TITLE
Color scheme - missed highlighted Variables after configuration

### ISSUE THREAD

**Issue by stevenanthonyrevo** [asottile/babi#128]
Tried to install the VScode theme with the example from readme and only the foreground colors are shown in the terminal.
Tested with VScode `theme-monokai` and no colors shown up for variables in python or HTML file. 

```
 ./bin/download-theme theme-monokai https://raw.githubusercontent.com/microsoft/vscode/main/extensions/theme-monokai/themes/monokai-color-theme.json
```

**Comment by asottile** [comment]
just guessing: you've probably done `sudo pip install` which puts babi into `/usr/local/bin` (whereas the prefix is actually `/usr`) -- this causes babi to not find its grammar files and is not a supported way to run the editor

try either: (1) use a virtualenv **(recommended)** or (2) install using `pip install --user`

**Comment by stevenanthonyrevo** [comment]
@asottile Thanks! I've tried within in a docker container centOS 7 with pip3 and wasn't able to get color changes but able to get the binary to run. 

I tried to install with `pip install --user` and it created a dir located here `../Library/Python/3.8/bin/babi`, is this correct?

**Comment by asottile** [comment]
not sure, it depends on the platform
