### ISSUE TITLE
Add (Python) language server for e.g. auto-complete, linter, type checking etc.

### ISSUE THREAD

**Issue by SommerEngineering** [asottile/babi#132]
It would be great if we could query the (Python) Language Server (https://github.com/palantir/python-language-server). This should, in principle, be no problem: The language servers are easy to use (cf. https://en.wikipedia.org/wiki/Language_Server_Protocol and https://blog.logrocket.com/how-to-use-the-language-server-protocol-to-extending-a-client-764da0e7863c/). It looks like we could even do the queries via stdout and stdin. Once implemented, the editor could cover many other languages as well (cf. https://microsoft.github.io/language-server-protocol/implementors/servers/), as long as the user configures the corresponding server and starts it locally.

**Comment by asottile** [comment]
this is planned, but it is extremely far off at this point
