### ISSUE TITLE
Jump to paragraph - feature request

### ISSUE THREAD

**Issue by workonfire** [asottile/babi#139]
Hello. Is there a possibility that you can add a **jump to paragraph** feature, like in nano?
This is what I mean:
![nano presentation](https://i.imgur.com/as6lXWT.gif)
I achieve this by pressing <kbd>Ctrl</kbd> + <kbd>Arrow Up</kbd>/<kbd>Arrow Down</kbd> and I don't see this feature anywhere in babi.

Also, I got used to pressing <kbd>Ctrl</kbd> + <kbd>Backspace</kbd> in order to delete a whole word, just like in other text editors (not in nano). This feature is very handy, so would you mind adding this as well?

**Comment by asottile** [comment]
the first shortcut is used by something more useful (scrolling) so that won't be added. the latter is possible, but ctrl+backspace key code isn't super portable across operating systems. are you interested in sending a patch?
