### ISSUE TITLE
Unable to highlight text on Mac OS

### ISSUE THREAD

**Issue by AshIsbitt** [asottile/babi#159]
<img width="239" alt="Screenshot 2021-09-11 at 21 53 27" src="https://user-images.githubusercontent.com/60970073/132961354-478297f7-9b9f-4127-af1b-4db3a21e21d4.png">

When I use SHIFT+ left/right arrow to highlight text, it appears highlighted in white (instead of in blue as is when I use a mouse) and trying to CMD+C to copy isn't working with that text. (CTRL+K still works to cut it, however). Unsure what other information to supply to make your life easier.

**Comment by asottile** [comment]
yeah so highlighting with the mouse highlights at the _terminal emulator_ level -- but the shift+arrows is internal to `babi` and is rendered using inversion.  your screenshot looks correct!
