### ISSUE TITLE
suspend tests fail on wsl arch tmux 2.9a

### ISSUE THREAD

**Issue by haydennyyy** [asottile/babi#16]
Whether it's because you're using old Tmux (a la #7) or not, I don't know.

Being on Arch, I get the latest versions of `tmux`, and that means I seem to get Babi errors early lol.

The error is caused in test_suspend. It's an AssertError waiting for 'babi v0' to show up.

**Comment by haydennyyy** [comment]
https://i.fluffy.cc/v1q7ql54lK4V2xprsb5S82Csnvl9lKVw.html

**Comment by asottile** [comment]
the weird thing about that output is it does seem to start it :S

**Comment by haydennyyy** [comment]
Exactly, I don't get it.

**Comment by asottile** [comment]
I wonder if it's bashrc or something 🤔

**Comment by haydennyyy** [comment]
What could the bashrc issue be?

**Comment by asottile** [comment]
if it takes too long to start for instance -- maybe try disabling the bashrc in the testsuite -- there's probably an argument to `bash` to do so

**Comment by haydennyyy** [comment]
I use ZSH mainly so I could just move the bashrc.

**Comment by asottile** [comment]
right, I'm suggesting a code patch you could contribute

**Comment by asottile** [comment]
I believe the flag is `--norc` and you can kill the `env PS1=$` stuff -- I don't think it ever worked as I intended it to

**Comment by haydennyyy** [comment]
This is weird. I cracked out my old Arch laptop's SSD and threw it into my new laptop, just to give this test a whirl on a full Arch install, and I think this might be just my WSL install, because on the Arch laptop all 63 tests pass.

**Comment by asottile** [comment]
I can get these tests to fail with `sleep 2` in my `~/.bashrc`

**Comment by asottile** [comment]
via #17
