### ISSUE TITLE
PR #180 breaks the saving of dot files :)

### ISSUE THREAD

**Issue by int3l** [asottile/babi#183]
Babi version: `0.0.25`

Steps to reproduce:

```bash
touch .test
babi .test
# Ctrl - X
```

Error message:
```text
cannot save file: [Errno 2] No such file or directory: ''
```

**Comment by asottile** [comment]
actually, appears it breaks saving all relative files -- going to revert CC @ClasherKasten

**Comment by asottile** [comment]
via c4853f26e433f61493ee4e68de9eb3f10fc8f47e

**Comment by int3l** [comment]
@asottile I think that it just needs the absolute path lookup:

```python
dir_path = os.path.dirname(os.path.abspath(self.file.filename))
os.makedirs(dir_path, exist_ok=True)
```

And the tests needs to be updated :)
