### ISSUE TITLE
Default color scheme doesn't work on macos

### ISSUE THREAD

**Issue by aliakseip** [asottile/babi#234]
Hey Anthony,

It seems that default color scheme doesn't work on macos.

<img width="389" alt="Screenshot 2022-04-11 at 19 59 22" src="https://user-images.githubusercontent.com/4150982/162801320-2a423aa8-3ba3-4727-9b75-626101a3e1db.png">
<img width="248" alt="Screenshot 2022-04-11 at 19 59 55" src="https://user-images.githubusercontent.com/4150982/162801323-cd3703fe-06c2-492a-b211-18db340f5834.png">

**Comment by asottile** [comment]
it works fine for me -- how did you install babi?  I suspect you did `sudo pip install` or some-such -- I'd recommend installing into a virtualenv (and [never using global pip / etc.](https://youtu.be/O390_abzo08))

personally I use:

```
virtualenv ~/opt/venv
~/opt/venv/bin/pip install babi
mkdir -p ~/bin
ln -sf ~/opt/venv/bin/babi ~/bin/
```

and then have `export PATH="$HOME/bin:$PATH"` in my shell startup files (bashrc / zshrc / etc.)

**Comment by aliakseip** [comment]
It also works fine, thanks. 
I also propose to update README.md for babi. Can I create a PR?

**Comment by asottile** [comment]
maybe just a quick note [here](https://github.com/asottile/babi#installation) -- "babi works best in a virtualenv" or something like that
