### ISSUE TITLE
Paste operation for emojis doesn't work in Windows

### ISSUE THREAD

**Issue by int3l** [asottile/babi#252]
This issue is only for reference, so people can find it if needed (feel free to close it if you don't want to investigate it).

Reproduction steps:

1. Copy emoji or sequence of emojis from browser or another Windows program. For example: `🙃`
1. Open babi (under CMD or PowerShell).
1. Try to paste in the terminal either via keyboard shortcut (`Ctrl + V` / `Shift + Insert`), right mouse click or via the context menu `Win key + .`
1. In most cases, babi reports errors like:

```text
unknown key: Key(wch='\ude43', keyname=b'UNKNOWN KEY')
```

As a workaround - you can open the same file in notepad or other editor in order to paste the emoji.
Since there is no rendering issues, you can reopen the same file in babi to continue the editing.

PS: I am not sure if this platform specific behaviour is caused by `windows-curses` implementation or by Windows itself.

**Comment by asottile** [comment]
yeah I think this is just because windows console and or windows curses doesn't properly support utf-8 -- it doesn't even work when pasting just `echo ☃` either without having babi involved
