### ISSUE TITLE
Word Wrapping

### ISSUE THREAD

**Issue by techtuner** [asottile/babi#253]
Hello,
I want to use babi for taking down notes. I am using a laptop so I reduce the windows to fit both the video and the editor. While doing so some of the notes extend the screen and I will have to keep scrolling to the end to check the notes. It would be helpful if you could add word wrap by default to the editor so that we do not have to keep scrolling.
Thank You

**Comment by asottile** [comment]
nope, sorry I think word wrapping is bad
