### ISSUE TITLE
babi not using babi_grammars when installed in a venv

### ISSUE THREAD

**Issue by MohrJonas** [asottile/babi#287]
I have babi installed in a venv (in my case located in `~/babi/venv`). The problem is that syntax highlighting is not working (babi_grammars is installed in `~/babi/venv/lib/python3.10/site-packages`).
After some digging around, it seems that the problem is that babi is looking for grammar files in `venv/share/babi/grammar_v1` and `~/.local/share/babi/grammar_v1`, both of which don't exist

**Comment by asottile** [comment]
how did you install it in a venv? can you show the fine structure of your virtualenv?

**Comment by MohrJonas** [comment]
I installed it like that:
- Clone the repo to `~/babi`
- create a venv in `~/babi/venv`
- activate the venv
- install babi with `python3 setup.py install`
- run babi with `babi`

The reason I installed it like that instead of using the babi package is to do some development myself.

The venv looks like that:
.
├── bin
│   ├── activate
│   ├── babi
│   ├── pip
│   ├── python3 -> /usr/bin/python3
│   ├── python3.10 -> python3
├── include
├── lib
│   └── python3.10
│       └── site-packages
│           └──  babi_grammars-0.0.50-py3.10.egg
│           ├── babi-1.5.3-py3.10.egg
├── lib64 -> lib
└── pyvenv.cfg

(Some files omitted for readability)

**Comment by asottile** [comment]
`python setup.py install` is not how to install packages -- use `pip`
