### ISSUE TITLE
unknown key Error

### ISSUE THREAD

**Issue by ibar2** [asottile/babi#295]
it shows these error when ever I try to type in quote marks and closing curly braces

closing curly braces
`unknown key: Key(wch='\x00', keyname=b'^@')
`
single quote mark
`unknown key: Key(wch=530, keyname=b'SHF_PADENTER') `

double quote mark
`unknown key: Key(wch=460, keyname=b'CTL_PADENTER')`

Versions
```
babi==1.5.3
babi-grammars==0.0.50
cffi==1.15.1
identify==2.5.24
onigurumacffi==1.2.0
pycparser==2.21
windows-curses==2.3.1
```

**Comment by asottile** [comment]
this is a bug with windows curses -- I noticed this as well but there's nothing that I can do about it sadly

**Comment by ibar2** [comment]
and the problem is with the `windows-curses==2.3.1`, 
on other computer i have i downgraded the `windows-curses to 2.3.0` and every seemed to work.

**Comment by ibar2** [comment]
yeah i downgraded window curses to 2.3.0 and seemed to work
