### ISSUE TITLE
trailing whitespace

### ISSUE THREAD

**Issue by asottile** [asottile/babi#3]
how to make this render properly?

**Comment by haydennyyy** [comment]
I think the only way would be either line numbers or like a line of dashes underneath the last line of the file. But I think line numbers would be MUCH better.

**Comment by asottile** [comment]
right now it doesn't render at all -- nano does somehow but I haven't figured it out -- I can probably show this on stream to explain it's very hard to explain in text :)

**Comment by asottile** [comment]
I made a SO post with a reproducer here: https://stackoverflow.com/q/59521039/812183

**Comment by asottile** [comment]
this is now "solved" on master, but now has the opposite problem -- deleting trailing whitespace leaves it behind

nano seems to have the same bug so "good enough" I guess

**Comment by asottile** [comment]
![Capture26](https://user-images.githubusercontent.com/1810591/76674674-53355200-656f-11ea-994c-17021c9de1a6.PNG)


here's what it looks like on the highlighting branch
