### ISSUE TITLE
tab size

### ISSUE THREAD

**Issue by asottile** [asottile/babi#4]
is this even available in python? do I need ctypes shenanigans? should I make a PR to cpython to add this api?

**Comment by asottile** [comment]
I did add `curses.set_tabsize` for python3.9 here: https://github.com/python/cpython/pull/16938

**Comment by asottile** [comment]
probably just implement this in code and not rely on the curses tab width stuff -- probably easier that way

**Comment by haydennyyy** [comment]
I would default this to 4, that's the most common one. Then in a potential `.babirc` let users set that independently.

**Comment by asottile** [comment]
this was done at some point and is now "configurable" thanks to #69 -- I'll eventually add some sort of rcfile to make this a little easier
