### ISSUE TITLE
Weird characters after saving and reopening files.

### ISSUE THREAD

**Issue by brynphillips** [asottile/babi#51]
```
print("hello` world"!) #hello world!^M

^M

^M

def now(words):^M

    print(words)^M

^M

def("hell yeah!")^M

^M

^M

^M
```

Seems that while using babi on Windows when opening and saving, then reopening the file I create a bunch of ^M. I can recreate both ways to exit, via :q and ctrl + x.

**Comment by asottile** [comment]
thanks for the report!  turned out to be a very easy fix :)
