### ISSUE TITLE
CSON missing from dependencies

### ISSUE THREAD

**Issue by juancarlospaco** [asottile/babi#66]
https://github.com/asottile/babi#setting-up-syntax-highlighting

```console
$ ./bin/download-theme vs-dark-asottile https://gist.github.com/asottile/b465856c82b1aaa4ba8c7c6314a72e13/raw/22d602fb355fb12b04f176a733941ba5713bc36c/vs_dark_asottile.json

Traceback (most recent call last):
  File "./bin/download-theme", line 11, in <module>
    import cson

ModuleNotFoundError: No module named 'cson'

$

```

MonkaS

**Comment by asottile** [comment]
the download-theme script is not distributed with babi so it is not a dependency -- it is intentionally left out such that it isn't unnecessarily included

you've edited the stacktrace though, it tells you what to do :P

https://github.com/asottile/babi/blob/afe461372e1e3236256b9d39e264392039fdba94/bin/download-theme#L11

**Comment by juancarlospaco** [comment]
It is by definition a Dev-Dependency.
I installed the dev dependencies.

**Comment by asottile** [comment]
it's not needed to run the tests so it's not a dev dependency :)

**Comment by juancarlospaco** [comment]
`setup.py` has `tests_require` for dependencies needed to run the tests,
maybe `cson` can be on a `extras_require` on the future.

**Comment by asottile** [comment]
nah, the script isn't part of babi or the tests or even necessary, `curl` works just as well and the error message includes exactly what you need to do to fix it if you do happen to run it.  adding packaging metadata for something that isn't packaging is not correct
