### ISSUE TITLE
hang on style tags in html

### ISSUE THREAD

**Issue by asottile** [asottile/babi#73]
typing this causes an infinite hang

```html
<!doctype html> 
<html>
<head>
    <style>
    </style
```

and can only be killed with `TERM`

**Comment by AndrewLaneX** [comment]
This breaks it too.

```javascript
class S {
    something() {
        let
        try {
        } 
```

**Comment by asottile** [comment]
@AndrewLaneX what file extension is that, I couldn't get that to hang when pasted 🤔

**Comment by AndrewLaneX** [comment]
@asottile it happens with `.js` or `.ts`.
