### ISSUE TITLE
syntax highlighting

### ISSUE THREAD

**Issue by asottile** [asottile/babi#8]
gotta make it happen eventually

the hint that chat gave me is to implement it using `textmate` syntax -- this is apparently what vscode does and makes it easy to get a bunch of existing syntax highlighting working quickly

gotta parse that format though 🤔 (and then implement the actual tokenization, etc.)

**Comment by haiden77** [comment]
Basbi LGBT edition
![image](https://user-images.githubusercontent.com/57046895/68534845-6d092300-034a-11ea-82e7-dc3ab1a6e005.png)

**Comment by haiden77** [comment]
#22 fixes

**Comment by haydennyyy** [comment]
`pygments` has a lexer that converts colours to ANSI colour codes, if you're interested. Replace the file string with a parsed version through `pygments`

**Comment by asottile** [comment]
this function seems helpful, idk why I didn't see it before?

https://docs.python.org/3/library/curses.html#curses.window.chgat

**Comment by asottile** [comment]
here's a demo of using 256 color escapes and producing the 256 color table:

```python
from typing import Dict
from typing import NamedTuple

C_256 = '\x1b[38;5;{c}m'
C_TRUE = '\x1b[38;2;{r};{g};{b}m'
C_RESET = '\x1b[m'


class Color(NamedTuple):
    r: int
    g: int
    b: int


def _table_256() -> Dict[Color, int]:
    def _incr(n: int) -> int:
        if n == 0:
            return 95
        else:
            return n + 40

    ret = {}
    i = 16
    r = g = b = 0
    ret[Color(r, g, b)] = i
    while (r, g, b) != (255, 255, 255):
        i += 1
        if b == 255 and g == 255:
            r, g, b = _incr(r), 0, 0
        elif b == 255:
            g, b = _incr(g), 0
        else:
            b = _incr(b)
        ret[Color(r, g, b)] = i
    for i in range(24):
        v = 10 * i + 8
        ret[Color(v, v, v)] = 232 + i
    return ret


TABLE_256 = _table_256()

print('256 color:')
for i in range(16, 256):
    print(f'{C_256.format(c=i)}X{C_RESET}', end='')
print()
print('256 color (as true color):')
for c in TABLE_256:
    print(f'{C_TRUE.format(**c._asdict())}X{C_RESET}', end='')
print()
```

___

true color can be detected using [`curses.can_change_color()`](https://docs.python.org/3/library/curses.html#curses.can_change_color)

unfortunately, it seems `screen` / `tmux` don't let on that they support true color:

```console
$ python3 -c 'import curses; print(curses.wrapper(lambda _: curses.can_change_color()))'
True
$ TERM=screen-256color python3 -c 'import curses; print(curses.wrapper(lambda _: curses.can_change_color()))'
False
```

though it seems that tmux supports true color just fine (???)

either way, there'll probably be three modes that highlighting will be applied:
- terminal supports true colors => use true color
- terminal supports 256 colors => approximate theme colors to 256 color table
- otherwise => disable colors (maybe use 8 color or 16 color?)

**Comment by asottile** [comment]
the first version of this is now in master: 697b012027eeb3a5ceec71cfbaa9133895ab93d4
