### ISSUE TITLE
Babi crashes on cmd +, or cmd - in MacOS

### ISSUE THREAD

**Issue by brynphillips** [asottile/babi#80]
Babi .12 crashes on cmd + and cmd - on MacOS X.

<img width="892" alt="Screen Shot 2020-07-18 at 15 18 04" src="https://user-images.githubusercontent.com/17993329/87862906-f6c1b500-c909-11ea-9535-5ab653d8769b.png">

**Comment by brynphillips** [comment]
I might be able to fix this if I follow a similar solution to #67. I'll give it a try if you don't mind.

**Comment by asottile** [comment]
sounds good, maybe try a retrying loop?

**Comment by asottile** [comment]
nice!  looks like I "accidentally" fixed this in 1.1.0 via #202

thanks again for the issue and first pass at a patch!
