### ISSUE TITLE
Use commands for everything with default keymap sets

### ISSUE THREAD

**Issue by haydennyyy** [asottile/babi#9]
You've said on stream that you can use Ctrl+X to close, type `:q`, or use the emacs thing...

What if you stick to creating a set of commands, but create default keymaps for each of those. Like, on setup, ask the user what editor they're most comfy with. If they say nano, add a set of keymaps that are specific to Nano, like ctrl+x, ctrl+o, ctrl+f, etc. If they say emacs, add that keymap set, and if they say vim, leave them to set their own. Obviously within reason.

That'd make it approachable by everyone.

I'd help implement this but it's Python. No.

**Comment by asottile** [comment]
for now I'm mostly writing this for me, once I'm happy with it I might look into expanding the functionality further -- but until then it won't really have any configuration

eventually though!

**Comment by haydennyyy** [comment]
An idea for mapping commands (not keymaps yet) would be something like this:

```python
COMMANDS = {}

def command(name, desc):
    def command_generator(func):
        COMMANDS[name] = { 'description': desc, 'run': func }
    return command_generator

@command('a', 'Hello world function')
def a_command():
    print("Hello, world!")

@command('w', 'Writes to the file')
def write_command():
    print("Write")

@command('q', 'Quits Babi')
def quit_command():
    print("Quit")

def main():
    for name, v in COMMANDS.items():
        print(f'{name} -> {v["description"]}')

main()
```

**Comment by asottile** [comment]
yeah I don't know how much of the commands I'll actually implement, since I really only use like `:sort` and `:qall!`

that structure is similar to how the twitch chat bot works

**Comment by haydennyyy** [comment]
@asottile That would be because I used it as a base to figure out what I was doing lol
