### ISSUE TITLE
backspacing blank line at end of file doesn't work

### ISSUE THREAD

**Issue by asottile** [asottile/babi#99]
- `echo -en 'foo\n\n' > t`
- `babi t`
- <kbd>ctrl+end</kbd>
- <kbd>backspace</kbd>
- <kbd>ctrl+s</kbd>
- <kbd>ctrl+x</kbd> (close babi)
- `babi t`  (reopen the file)
- the extra blank line is still there

this used to work, hmmm

**Comment by MiConnell** [comment]
If it helps at all it looks like even if there's no newline at the end of a file babi still renders the newline.

File open in Sublime
<img width="299" alt="Screen Shot 2020-11-06 at 4 19 36 PM" src="https://user-images.githubusercontent.com/14168559/98425983-034e5280-204c-11eb-9fa0-13364aaee2d5.png">

File open in babi
<img width="345" alt="Screen Shot 2020-11-06 at 4 20 07 PM" src="https://user-images.githubusercontent.com/14168559/98425991-0cd7ba80-204c-11eb-900a-2f02b192a83e.png">

Backspacing the newline at the end in babi doesn't seem to actually remove it as the down arrow still allows me to go down. It also doesn't show any unsaved changes if I backspace the newline.

It also looks like a newline gets added after just opening and saving the file in babi (without actually modifying anything). 

I can try to work on this if you'd like.

**Comment by asottile** [comment]
the render of the newline at the end of the file is intentional -- this is so you can write code at the end easily -- `nano` does the same thing here -- that's not the bug
